#!/usr/bin/env bash
# Display information about subdomains.

domain_information() {
    local subdomain="$2"
    local domain="$1"
    local query_result

    query_result=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$subdomain $query_result" | awk '{print "The subdomain " $domain " is a " $subdomain " record and points to " $3}'
}

if [ "$#" == 1 ]; then
    domain_information "$doamin" "www"
    domain_information "$doamin" "lb-01"
    domain_information "$doamin" "web-01"
    domain_information "$doamin" "web-02"
elif [ "$#" == 2 ]; then
    domain_information "$doamin" "$subdomain"
