#!/usr/bin/env bash
# Display information about subdomains.

domain_information() {
    local query_result=$(dig "$2"."$1" +short)
    local record_type=$(dig "$2"."$1" | awk '/ANSWER SECTION:/ {getline; print $4}')

    echo "The subdomain $2 is a $record_type record and points to $query_result"
}

if [ "$#" -eq 1 ]; then
	subdomains=("www" "lb-01" "web-01" "web-02")

	for subdomain in "${subdomains[@]}"; do
		domain_information "$1" "$subdomain"
	done
elif [ "$#" -eq 2 ]; then
	domain_information "$1" "$2"
