#!/usr/bin/env bash
# Install nginx web server

# Update package information
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic through UFW
sudo ufw allow 'Nginx HTTP'

# Restart Nginx to apply changes
sudo service nginx start

# Create a simple index page
echo "Hello World!" > /var/www/html/index.html
