#!/usr/bin/env bash
# Redirection

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Start Nginx service
sudo service nginx start

# Create a file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure Nginx with a new string
my_new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/tebogondaba.tech permanent;"
sudo sed -i "s/server_name _;/$my_new_string/" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
