#!/usr/bin/env bash
# Install load balancer

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy in default configuration
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# Backup original configuration
mv /etc/haproxy/haproxy.cfg{,.original}

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
# HAProxy Global Configuration
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

# Default Configuration
defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client  30000
    timeout server  30000

# Frontend Configuration
frontend http-in
    timeout client 30000
    bind 0:80
    default_backend servers

# Backend Configuration
backend servers
    timeout connect 3000
    timeout server 30000
    balance roundrobin
    server 346505-web-01 54.237.94.18:80 check
    server 346505-web-02 100.26.154.55:80 check
EOL

# Restart HAProxy
sudo service haproxy restart
