#!/usr/bin/env bash
# Install load balancer

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get -y install haproxy

# HAProxy configuration
haproxy_config=frontend
\tbind *:80
\tmode http
\tdefault_backend web-backend

backend web-backend
\tbalance roundrobin
\tserver 346505-web-01 54.237.94.18:80 check
\tserver 346505-web-02 100.26.154.55:80 check

# Update HAProxy configuration file
echo -e "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
