#!/usr/bin/env bash
# Nginx port 80

# Define variables for better maintainability
NGINX_CONF_PATH="/etc/nginx/sites-enabled/default"

# Replace port 8080 with 80 in the Nginx configuration
sed -i 's/8080/80/g' "$NGINX_CONF_PATH"

# Test the Nginx configuration before restarting
nginx -t

# Restart Nginx service only if the configuration test passes
sudo service nginx restart
