#!/usr/bin/env bash
# Nginx port 80

# Define variable
NGINX_CONF_PATH="/etc/nginx/sites-enabled/default"

# Replace port 8080 with 80 in the Nginx configuration
rm $NGINX_CONF_PATH
ln -s /etc/nginx/sites-available/default $NGINX_CONF_PATH

# Restart Nginx service only if the configuration test passes
sudo service nginx restart
