#!/usr/bin/env bash
# Configure Nginx short and sweet.

# Define variables
NGINX_SITES_AVAILABLE="/etc/nginx/sites-available/default"
NGINX_SITES_ENABLED="/etc/nginx/sites-enabled/default"
# Create a symbolic link to the available configuration,
# force if it already exists
ln -sf "$NGINX_SITES_AVAILABLE" "$NGINX_SITES_ENABLED"
# Restart Nginx service | Stop the first Nginx process found
service nginx start | kill $(pgrep 'nginx' | head -1)
