#!/usr/bin/env bash
# Configures the container to NGINX as NGINX listening on all active IPs on port 8080
sudo pkill -o apache2
sudo chmod 744 /etc/nginx/nginx.conf
sudo sed -i '3i\user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo service nginx restart
